{% set name = "prescient-sdk" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/prescient_sdk-{{ version }}.tar.gz
  sha256: 8ccce0e76e640799d1391c94f38144e5a66a8fbb880d4f9659cbeca549a6307b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - boto3 >=1.35.19
    - msal >=1.31.0
    - pydantic-settings >=2.5.2

test:
  imports:
    - prescient_sdk
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://sparkgeo.github.io/prescient-sdk
  summary: A Python SDK for integrating with Prescient services
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/sparkgeo/prescient-sdk

extra:
  recipe-maintainers:
    - underchemist
    - gnieuwenhuis
    - michaelconnor00
