{% set name = "prescient-sdk" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/prescient_sdk-{{ version }}.tar.gz
  sha256: 7f51f56b5b22cf914fb613129b7d89ccc6dc4b109a7253eb3c5f106849d748aa

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - hatchling
    - pip
  run:
    - python >=3.9
    - boto3 >=1.35.19
    - msal >=1.31.0
    - pydantic-settings >=2.5.2

test:
  imports:
    - prescient_sdk
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://sparkgeo.github.io/prescient-sdk
  summary: A Python SDK for integrating with Prescient services
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/sparkgeo/prescient-sdk

extra:
  recipe-maintainers:
    - gnieuwenhuis
    - michaelconnor00
